#!/bin/bash

# dashboard
rm -f dashboard.js dashboard.min.js
cat ../js/*.js ../js/dashboard/*.js >> dashboard.js
yuicompressor dashboard.js -o dashboard.min.js

rm -f dashboard.css dashboard.min.css
cat ../css/*.css ../css/dashboard/*.css >> dashboard.css
yuicompressor dashboard.css -o dashboard.min.css

# profile
rm -f profile.js profile.min.js
cat ../js/*.js ../js/profile/*.js >> profile.js
yuicompressor profile.js -o profile.min.js

rm -f profile.css profile.min.css
cat ../css/*.css ../css/profile/*.css >> profile.css
yuicompressor profile.css -o profile.min.css
