#!/bin/bash
rm -f dashboard.js dashboard.min.js
cat ../js/*.js ../js/dashboard/*.js >> dashboard.js
yuicompressor dashboard.js -o dashboard.min.js

rm -f dashboard.css dashboard.min.css
cat ../css/*.css ../css/dashboard/*.css >> dashboard.css
yuicompressor dashboard.css -o dashboard.min.css
